version: '3.8'

services:
  api_backend:
    image: leonardomulticloud/challenge-stock-meo-backend:v1.0
    container_name: api_backend
    ports:
      - "8080:8080"
    environment:
      - API_KEY=123
    restart: unless-stopped
